# Generated by Django 5.0.1 on 2025-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_user_email_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('owner', 'Shop Owner'), ('managers', 'Manager'), ('staffs', 'Staff'), ('customers', 'Customer')], default='customers', max_length=20),
        ),
    ]
