# Generated by Django 5.0.1 on 2025-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='staff_images/blank_user_profile.png', null=True, upload_to='staff_images/'),
        ),
    ]
