# Generated by Django 5.0.1 on 2025-03-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_remove_invoice_due_date_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='unit_price',
        ),
    ]
