# Generated by Django 5.0.1 on 2025-02-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_category_slug_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
