# Generated by Django 5.0.1 on 2025-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_invoiceitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default='Nil', max_length=255),
        ),
    ]
