# Generated by Django 5.0.1 on 2025-03-05 20:08

import userauths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_invoiceitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=userauths.utils.generate_invoice_number, max_length=50, unique=True),
        ),
    ]
