# Generated by Django 5.0.1 on 2025-03-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_review'),
        ('ecommerce', '0011_alter_invoice_invoice_number'),
    ]

    operations = [
    ]
