# Generated by Django 5.0.1 on 2026-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_add_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_format',
            field=models.CharField(choices=[('large_letter', 'Large Letter'), ('small_parcel', 'Small Parcel'), ('medium_parcel', 'Medium Parcel')], default='small_parcel', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.CharField(choices=[('standard', 'Standard (20%)'), ('zero', 'Zero (0%)')], default='standard', max_length=20),
        ),
    ]
