# Generated by Django 5.0.1 on 2026-02-14 00:00

from django.db import migrations, models
from django.utils import timezone
import secrets


def _generate_unique_order_number(Order):
    date_part = timezone.now().strftime('%Y%m%d')
    while True:
        token = secrets.token_hex(4).upper()
        value = f"ORD-{date_part}-{token}"
        if not Order.objects.filter(order_number=value).exists():
            return value


def populate_order_numbers(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(order_number__isnull=True):
        order.order_number = _generate_unique_order_number(Order)
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_stripe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(populate_order_numbers, migrations.RunPython.noop),
    ]
