# Generated by Django 5.0.1 on 2026-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
